input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  if [level] {
    mutate {
      lowercase => ["level"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-demo-%{+yyyy.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
